version: '3.8'

services:
  app:
    build:
      context: .
      target: build
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 